### PR TITLE
Support inv on diagonal matrices from unitranges

### LINKED ISSUE #176: Can't invert Diagonal{Int, InfUnitRange}
```julia
julia> using InfiniteArrays, LinearAlgebra

julia> A = Diagonal(1:∞)
ℵ₀×ℵ₀ Diagonal{Int64, InfiniteArrays.InfUnitRange{Int64}} with indices OneToInf()×OneToInf():
 1  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  …  
 ⋅  2  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅     
 ⋅  ⋅  3  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅
 ⋅  ⋅  ⋅  4  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅
 ⋅  ⋅  ⋅  ⋅  5  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅  6  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  …
 ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  7  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅
 ⋮              ⋮              ⋮              ⋮              ⋮              ⋮              ⋮              ⋮              ⋮              ⋮  ⋱

julia> inv(A) # hangs because it hits the finite method
ERROR: InterruptException:
Stacktrace:
 [1] _vec_resizedata!(B::LazyArrays.CachedArray{Float64, 1, Vector{Float64}, Zeros{Float64, 1, Tuple{…}}}, n::Int64)
   @ LazyArrays C:\Users\User\.julia\packages\LazyArrays\MLFsy\src\cache.jl:230
 [2] resizedata!
   @ C:\Users\User\.julia\packages\LazyArrays\MLFsy\src\cache.jl:251 [inlined]
 [3] resizedata!
   @ C:\Users\User\.julia\packages\LazyArrays\MLFsy\src\cache.jl:218 [inlined]
 [4] setindex!
   @ C:\Users\User\.julia\packages\LazyArrays\MLFsy\src\cache.jl:82 [inlined]
 [5] inv(D::Diagonal{Int64, InfiniteArrays.InfUnitRange{Int64}})
   @ LinearAlgebra C:\Users\User\.julia\juliaup\julia-1.10.4+0.x64.w64.mingw32\share\julia\stdlib\v1.10\LinearAlgebra\src\diagonal.jl:722
 [6] top-level scope
   @ REPL[11]:1
Some type information was truncated. Use `show(err)` to see complete types.

julia> Diagonal(inv.(A.diag))
ℵ₀×ℵ₀ Diagonal{Float64, LazyArrays.BroadcastVector{Float64, typeof(inv), Tuple{InfiniteArrays.InfUnitRange{Int64}}}} with indices OneToInf()×OneToInf():
 1.0   ⋅    ⋅         ⋅     ⋅    ⋅         ⋅         ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   …  
  ⋅   0.5   ⋅         ⋅     ⋅    ⋅         ⋅         ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅
  ⋅    ⋅   0.333333   ⋅     ⋅    ⋅         ⋅         ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅
  ⋅    ⋅    ⋅        0.25   ⋅    ⋅         ⋅         ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅
  ⋅    ⋅    ⋅         ⋅    0.2   ⋅         ⋅         ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅      
  ⋅    ⋅    ⋅         ⋅     ⋅   0.166667   ⋅         ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   …
  ⋅    ⋅    ⋅         ⋅     ⋅    ⋅        0.142857   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅
 ⋮                              ⋮                                  ⋮                        ⋮                        ⋮                        ⋱
```

### PR DESCRIPTION
**Pull request by DanielVandH**
Fixes #176

### CODE REVIEW

**Comment by jishnub** [comment]
Won't this change the behavior from throwing a `SingularException` to returning an `Inf` if one of the values is zero?

**Comment by DanielVandH** [comment]
Technically yes, although this `inv` never worked in the first place for nonsingular matrices. Similar methods for `inv` don't throw, e.g.

```julia
julia> A = Diagonal((0:∞) .+ (0:∞)) # force non-infrange type
ℵ₀×ℵ₀ Diagonal{Int64, LazyArrays.BroadcastVector{Int64, typeof(+), Tuple{InfiniteArrays.InfUnitRange{Int64}, InfiniteArrays.InfUnitRange{Int64}}}} with indices OneToInf()×OneToInf():
 0  ⋅  ⋅  ⋅  ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅  ⋅  ⋅  ⋅  …
 ⋅  2  ⋅  ⋅  ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅  ⋅  ⋅  ⋅
 ⋅  ⋅  4  ⋅  ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅  ⋅  ⋅  ⋅
 ⋅  ⋅  ⋅  6  ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅  ⋅  ⋅  ⋅
 ⋅  ⋅  ⋅  ⋅  8   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅  ⋅  ⋅  ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅  10   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅  ⋅  ⋅  ⋅  …
 ⋅  ⋅  ⋅  ⋅  ⋅   ⋅  12   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅  ⋅  ⋅  ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅   ⋅   ⋅  14   ⋅   ⋅   ⋅   ⋅   ⋅  ⋅  ⋅  ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅   ⋅   ⋅   ⋅  16   ⋅   ⋅   ⋅   ⋅  ⋅  ⋅  ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅   ⋅   ⋅   ⋅   ⋅  18   ⋅   ⋅   ⋅  ⋅  ⋅  ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅   ⋅   ⋅   ⋅   ⋅   ⋅  20   ⋅   ⋅  ⋅  ⋅  ⋅  …
 ⋅  ⋅  ⋅  ⋅  ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅  22   ⋅  ⋅  ⋅  ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅  24  ⋅  ⋅  ⋅
 ⋮               ⋮                   ⋮                ⋮  ⋱

julia> inv(A)
ℵ₀×ℵ₀ Diagonal{Float64, LazyArrays.BroadcastVector{Float64, typeof(inv), Tuple{LazyArrays.BroadcastVector{Int64, typeof(+), Tuple{InfiniteArrays.InfUnitRange{Int64}, InfiniteArrays.InfUnitRange{Int64}}}}}} with indices OneToInf()×OneToInf():
 Inf    ⋅    ⋅     ⋅         ⋅      ⋅    ⋅         …
   ⋅   0.5   ⋅     ⋅         ⋅      ⋅    ⋅
   ⋅    ⋅   0.25   ⋅         ⋅      ⋅    ⋅
   ⋅    ⋅    ⋅    0.166667   ⋅      ⋅    ⋅
   ⋅    ⋅    ⋅     ⋅        0.125   ⋅    ⋅
   ⋅    ⋅    ⋅     ⋅         ⋅     0.1   ⋅         …
   ⋅    ⋅    ⋅     ⋅         ⋅      ⋅   0.0833333
   ⋅    ⋅    ⋅     ⋅         ⋅      ⋅    ⋅
   ⋅    ⋅    ⋅     ⋅         ⋅      ⋅    ⋅
   ⋅    ⋅    ⋅     ⋅         ⋅      ⋅    ⋅
   ⋅    ⋅    ⋅     ⋅         ⋅      ⋅    ⋅         …
   ⋅    ⋅    ⋅     ⋅         ⋅      ⋅    ⋅
   ⋅    ⋅    ⋅     ⋅         ⋅      ⋅    ⋅
  ⋮                                ⋮               
```

**Comment by jishnub** [comment]
Should a change like this go to `LinearAlgebra`? That way, we won't need to special case this for other infinite array types.

**Comment by dlfivefifty** [comment]
Test failure seems spurious

**Pull request merged**
