### PR TITLE
Restrict `vcat` to ranges of numbers

### PR DESCRIPTION
**Pull request by jishnub**
~Also, specialize `axes` for `InfRange`s, which is needed on Julia nightly~ moved to https://github.com/JuliaArrays/InfiniteArrays.jl/pull/141

### CODE REVIEW

**Comment by dlfivefifty** [comment]
This change doesn't make sense to me

**Comment by jishnub** [comment]
Some of this is to work around `SparseArrays` introducing method ambiguities in v1.10 (https://github.com/JuliaSparse/SparseArrays.jl/issues/431), but perhaps we may add extra methods instead of limiting existing methods.

**Comment by dlfivefifty** [comment]
Can this be closed?

**Comment by jishnub** [comment]
Let's leave this open until there's a decision on the `SparseArrays` side.  Ideally, no action is needed here.

**Pull request closed without merging**
